
services:
  es01:
    extends:
      file: ./elastic-backend/docker-compose.yml
      service: es01

  es02:
    extends:
      file: ./elastic-backend/docker-compose.yml
      service: es02

  search-ui:
    extends:
      file: ./search-ui/docker-compose.yml
      service: search-ui

volumes:
  es_data01:
    external: true
  es_data02:
    external: true

networks:
  elastic-net:
    external: true
